query MoviePopularList($page: Int = 1) {
  moviePopularList(page: $page) {
    page
    totalPages
    totalResults
    results {
      id
      title
      originalTitle
      originalLanguage
      overview
      posterPath
      backdropPath
      releaseDate
      genreIds
      voteCount
      voteAverage
      adult
    }
  }
}
